version: "3.9"

services:
  db:
    container_name: social-media-prod-db
    image: mongo:latest
    command: mongod
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  store:
    container_name: social-media-prod-store
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - store:/data

  api:
    image: akaluan/sm-api
    container_name: social-media-prod-api
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - store

  toxicity-service:
    image: akaluan/toxicity:0.0.3
    container_name: social-media-prod-toxicity-service

volumes:
  db: {}
  store: {}
