version: "3.9"

services:
  db:
    container_name: database
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    command: mongod
    volumes:
      - db:/data/db

  store:
    container_name: store
    image: redis:${REDIS_TAG}
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass ${STORE_PASSWORD}
    volumes:
      - store:/data

  api:
    build: .
    container_name: api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - store

volumes:
  db: {}
  store: {}
