apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api
  name: api-controller
spec:
  replicas: 2
  selector:
    name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - image: <YOUR-CONTAINER>
        name: api
        ports:
        - containerPort: 8000
          name: http-server